export const ACCOUNT = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOADING_ACCOUNT: 'LOADING_ACCOUNT',
  ACCOUNT_LOADED: 'ACCOUNT_LOADED',
  ACCOUNT_ERROR: 'ACCOUNT_ERROR',
  SET_CURRENT_USER: 'SET_CURRENT_USER',
};
